name: Angular CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'libs/**'
      - '.github/workflows/**'
      - 'angularfrontend/**'  # Ensure this path matches your repo structure

jobs:
  DeployDev:
    name: Build & Push Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Repository Files (Debug Step)
        run: |
          echo "Listing files in the repository"
          ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR, Build Image, Tag, and Push
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 058264124336.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t angular -f angularfrontend/angular/angular/Dockerfile angularfrontend/angular/
          docker tag angular:latest 058264124336.dkr.ecr.ap-south-1.amazonaws.com/angular:latest
          docker push 058264124336.dkr.ecr.ap-south-1.amazonaws.com/angular:latest
